Hw03 chessboard
ishapkin/home_work_basic_ishapkin pull request #3
Opened 2024-01-08 19:47 UTC by ishapkin

## Домашнее задание №3 «Шахматная доска»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x ] Я запустил `go mod tidy`.
- [ x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~25 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-01-09 05:36 UTC, vladislavmass requested changes
Хорошее начало, но программа работает некорректно по нескольким причинам
1) ширина в 2 раза больше высоты
2) результат ее работы не является шахматной доской
#### Результат работы программы
```
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
 # # # # # # # #
```
#### Ожидаемый результат
```
|#| |#| |#| |#| |
| |#| |#| |#| |#|
|#| |#| |#| |#| |
| |#| |#| |#| |#|
|#| |#| |#| |#| |
| |#| |#| |#| |#|
|#| |#| |#| |#| |
| |#| |#| |#| |#|

```

2024-01-09 05:42 UTC, ishapkin commented
1. В задании не указано, что должны быть какие-то еще символы кроме пробела и #:

"На каждой позиции либо пробел, либо #."

2. Зависит от настроек командой строки (межстрочный интервал) на каком терминале такой вывод?

2024-01-09 12:28 UTC, ishapkin commented
Изменения внесены, результат теперь такой:

2024-01-10 06:25 UTC, vladislavmass requested changes
Код некорректной себя ведет при нечетных значения. Например 5 и 7

2024-01-10 10:35 UTC, ishapkin commented
> Код некорректной себя ведет при нечетных значения. Например 5 и 7

Теперь так:
```
|#| |#| |#|
| |#| |#| |
|#| |#| |#|
| |#| |#| |
|#| |#| |#|
```

2024-01-10 10:42 UTC, vladislavmass approved these changes

2024-01-10 11:48 UTC, merged